### ISSUE TITLE
how to load objects

### ISSUE THREAD

**Issue by jlsfernandez** [blackjk3/threefab#13]
Hi you talk about load objects into scene but how can be done?

**Comment by blackjk3** [comment]
@jlsfernandez you can drag and drop a model exported in three.js format and it will load into the viewport.  If you want a tutorial on exporting a three.js model from blender I have one from my blog. http://www.kadrmasconcepts.com/blog/2012/01/24/from-blender-to-threefab-exporting-three-js-morph-animations/
