### ISSUE TITLE
less compiler

### ISSUE THREAD

**Issue by jterrace** [blackjk3/threefab#15]
Working on updating some things and noticed that you're using less. It looks like I should update the .less file and then recompile it to .css. What compiler are you using? When I use `lessc less/style.less css/style.css`, the diff of the css file looks like everything changed, so I think you must be using a different compiler or a different version. My version:

```
$ lessc --version
lessc 1.3.0 (LESS Compiler) [JavaScript]
```

**Comment by blackjk3** [comment]
I was using the LESS app for mac, so I believe when I last compiled 6 months ago it was at 1.2.0. Feel free to re-compile at 1.3.0 since the app is now on that version as well.

**Comment by jterrace** [comment]
Great, thanks.
