### ISSUE TITLE
Textures don't always assign right away

### ISSUE THREAD

**Issue by blackjk3** [blackjk3/threefab#3]
Investigate as to why even though a material has been refreshed sometimes a material does not display the assigned texture.

**Comment by blackjk3** [comment]
Ok, not fixed.  Currently i'm a little unsure how to get a dynamic texture to reload.  Drag and dropping 2x seems to always fix the problem.

Currently doing something like
selectedElement.material.program = null;
selectedElement.material.map = texture;

Will need to investigate further.

**Comment by mrdoob** [comment]
Make sure the texture has loaded before assigning it.

**Comment by blackjk3** [comment]
Ahhhhh! Silly me.  Sometimes a second pair of eyes helps.  Thanks!
